spring:
  application:
    name: calculator

server:
  port: 8080

calculate:
  averageDaysInMonth: 29.3
  tax: 13
  unpaidDays:
    - "01-01"
    - "01-02"
    - "01-03"
    - "01-04"
    - "01-05"
    - "01-06"
    - "01-07"
    - "01-08"
    - "02-23"
    - "02-24"
    - "02-25"
    - "03-08"
    - "03-09"
    - "03-10"
    - "05-09"
    - "04-10"
    - "04-11"
    - "04-12"
    - "06-12"
    - "11-04"
